const categories=['Trending','New','Telugu','Tamil','Hindi','English','BGM','Love','Sad','Devotional','Notification','Alarm','Instrumental'];
const palettes=[['#38246d','#1b6e91'],['#67264f','#25236d'],['#145965','#442568'],['#7d4b1d','#233d70'],['#512668','#1c6d69'],['#263b70','#62408a']];
const names=['Neon Horizon','Midnight Metro','Monsoon Echo','Velvet Sunrise','Orbit Signal','Coastal Drift','Golden Hour Loop','Rain on Glass','Cosmic Pulse','Quiet Bloom','Voltage Avenue','Afterglow Keys','Paper Planes','Cloudline','Lunar Arcade','Soft Focus','Electric Bloom','Dawn Runner','Magnetic North','Starlit Steps'];
const categoryMap=['BGM','Telugu','Love','English','BGM','Tamil','Hindi','Sad','Instrumental','Devotional','Notification','Love','English','Alarm','BGM','New','Trending','Telugu','English','Instrumental'];
const data=names.map((title,i)=>({id:i+1,title,artist:['Aarav Sounds','Mira Studio','Wave Rise Originals'][i%3],category:categoryMap[i],duration:`00:${String(18+(i*7)%29).padStart(2,'0')}`,downloads:[12400,9800,8700,7200,6900,5800,5300,4900][i%8],palette:palettes[i%palettes.length],icon:['◒','✦','◉','♢','∿','✧'][i%6]}));
let audio=null,current=null;
const $=s=>document.querySelector(s), toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
function wave(cls='mini-wave',count=28){return `<div class="${cls}">${Array.from({length:count},(_,i)=>`<i style="--h:${12+((i*17)%24)}%"></i>`).join('')}</div>`}
function card(r){return `<article class="ringtone-card" data-id="${r.id}"><div class="cover" style="background:linear-gradient(135deg,${r.palette[0]},${r.palette[1]})"><span class="cover-icon">${r.icon}</span></div><div class="card-top"><div class="card-title">${r.title}</div><button class="heart" data-fav="${r.id}" aria-label="Favorite">♡</button></div><div class="meta">${r.category} · ${r.duration} · ${r.artist}</div><div class="player-row"><button class="mini-play" data-play="${r.id}">▶</button>${wave()}<span class="downloads">${(r.downloads/1000).toFixed(1)}k</span></div><div class="card-foot"><span class="downloads">MP3 • cleared</span><button class="download" data-download="${r.id}">↓ Save</button></div></article>`}
function renderGrid(el,arr){$(el).innerHTML=arr.map(card).join('')}
function setup(){ $('#chips').innerHTML=categories.map((c,i)=>`<button class="chip ${i===0?'active':''}" data-category="${c.toLowerCase()}">${c}</button>`).join('');renderGrid('#trendingGrid',data.slice(0,8));renderGrid('#newGrid',data.slice(12,16));$('#categoryGrid').innerHTML=['Telugu','Tamil','Hindi','English','BGM','Love','Sad','Devotional','Notification','Alarm'].map((c,i)=>`<a class="category" href="#category/${c.toLowerCase()}"><strong>${c}</strong><span>${data.filter(x=>x.category.toLowerCase()===c.toLowerCase()).length+12} sounds</span><b>${['◉','∿','✦','♢','◒','♡','☾','✧','⌁','◌'][i]}</b></a>`).join('')}
function makeTone(id){const rate=22050,dur=3,buffer=new ArrayBuffer(44+rate*dur*2),view=new DataView(buffer);const write=(o,s)=>[...s].forEach((c,i)=>view.setUint8(o+i,c.charCodeAt(0)));write(0,'RIFF');view.setUint32(4,36+rate*dur*2,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,rate,true);view.setUint32(28,rate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,rate*dur*2,true);for(let i=0;i<rate*dur;i++){let t=i/rate,env=Math.min(1,t*8)*Math.min(1,(dur-t)*8),v=Math.sin(2*Math.PI*(220+id*13)*t)*env;view.setInt16(44+i*2,v*26000,true)}return URL.createObjectURL(new Blob([buffer],{type:'audio/wav'}))}
function download(r){const a=document.createElement('a');a.href=makeTone(r.id);a.download=`wave-rise-${r.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.wav`;a.click();toast('Download started · rights-cleared demo audio');r.downloads++;}
function openDetail(r){current=r;$('#detailArt').style.background=`linear-gradient(135deg,${r.palette[0]},${r.palette[1]})`;$('#detailArt').textContent=r.icon;$('#detailCategory').textContent=`${r.category} · ${r.duration}`;$('#detailTitle').textContent=r.title;$('#detailArtist').textContent=`Created by ${r.artist} · ${r.downloads.toLocaleString()} downloads`;$('#seoCategory').textContent=r.category.toLowerCase();$('#detailWave').innerHTML=wave('waveform',42);$('#detailModal').classList.add('open');location.hash=`ringtone/${r.id}`}
function search(term){const found=data.filter(r=>[r.title,r.artist,r.category].join(' ').toLowerCase().includes(term.toLowerCase()));$('#resultTerm').textContent=`“${term}”`;$('#searchResults').hidden=false;renderGrid('#resultsGrid',found);$('#searchResults').scrollIntoView({behavior:'smooth'});if(!found.length)$('#resultsGrid').innerHTML='<div class="muted">No sounds found. Try “BGM”, “love”, or “Telugu”.</div>'}
document.addEventListener('click',e=>{const play=e.target.closest('[data-play]'),dl=e.target.closest('[data-download]'),fav=e.target.closest('[data-fav]'),cardEl=e.target.closest('.ringtone-card');if(play){const r=data.find(x=>x.id==play.dataset.play);if(audio){audio.pause();audio=null;document.querySelectorAll('.mini-play').forEach(b=>b.textContent='▶')}else{audio=new Audio(makeTone(r.id));audio.play();play.textContent='Ⅱ';audio.onended=()=>{audio=null;play.textContent='▶'}}}else if(dl){download(data.find(x=>x.id==dl.dataset.download))}else if(fav){fav.classList.toggle('on');fav.textContent=fav.classList.contains('on')?'♥':'♡';toast(fav.classList.contains('on')?'Added to favorites':'Removed from favorites')}else if(cardEl)openDetail(data.find(x=>x.id==cardEl.dataset.id));if(e.target.matches('[data-close]'))$('#detailModal').classList.remove('open');if(e.target.matches('[data-admin-close]'))$('#adminPanel').classList.remove('open')});
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();const v=$('#searchInput').value.trim();if(v)search(v)});$('#clearSearch').onclick=()=>$('#searchResults').hidden=true;$('#adminBtn').onclick=()=>$('#adminPanel').classList.add('open');$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');toast('Theme preference saved for this session')};$('#detailDownload').onclick=()=>download(current);$('#detailPlay').onclick=()=>{if(audio){audio.pause();audio=null;$('#detailPlay').textContent='▶'}else{audio=new Audio(makeTone(current.id));audio.play();$('#detailPlay').textContent='Ⅱ';audio.onended=()=>{$('#detailPlay').textContent='▶';audio=null}}};$('#detailShare').onclick=async()=>{try{await navigator.share({title:current.title,url:location.href})}catch{await navigator.clipboard.writeText(location.href);toast('Link copied')}};$('#copyLink').onclick=async()=>{await navigator.clipboard.writeText(location.href);toast('Link copied to clipboard')};document.addEventListener('click',e=>{const c=e.target.closest('[data-category]');if(c){const term=c.dataset.category;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');if(term==='trending')renderGrid('#trendingGrid',data.slice(0,8));else if(term==='new')renderGrid('#trendingGrid',data.slice(12));else search(term)}});$('#adminForm').onsubmit=e=>{e.preventDefault();toast('Submitted for rights review · demo mode');e.target.reset()};setup();
